name: JS Test Slim

on:
  workflow_dispatch: # Manual trigger

jobs:
  example-job:
    runs-on: ubuntu-slim

    steps:
      - name: download repository
        uses: actions/checkout@v6

      - name: js setup
        uses: actions/setup-node@v6
        with:
          node-version: ">=24.x"

      - name: run script
        id: script
        run: echo "hello world" >> $GITHUB_STEP_SUMMARY