name: Python Test

on:
  workflow_dispatch: # Manual trigger

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: download repository
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # latest Python 3 release

      - name: run script
        run: python test.py
